import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MSISection from '../components/section'
import MSILayouts from '../Layouts'
import NowPlaying from './nowplaying'
import Popular from './popular'
import TopRated from './toprated'
import Upcoming from './upcoming'

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

      <MSILayouts>
        <MSISection category='now' slice seeall='/nowplaying' link='/' title='Now Playing'/>
        <MSISection category='upcoming' slice seeall='/upcoming' link='/' title='Upcoming'/>
        <MSISection category='popular' slice seeall='/popular' link='/' title='Popular'/>
        <MSISection category='top' slice seeall='/toprated' link='/' title='Top Rated'/>
        {/* <NowPlaying slice seeall='/nowplaying' link='/details' title='Now Playing'/>
        <Upcoming slice seeall='/upcoming' link='/details' title='Up Coming'/>
        <Popular slice seeall='/popular' link='/details' title='Popular'/>
        <TopRated slice seeall='/toprated' link='/details' title='Top Rated'/> */}
    </MSILayouts>
  )
}

export default Home

// export async function getServerSideProps(ctx:any) {
//   const [nowPlaying,upComing,popular,topRated] = await Promise.all([
//     fetch('')
//   ])
//   return{
//     props:{

//     }
//   }
// }